### ISSUE TITLE
Add "@codemirror/state" to peerDependencies ?

### ISSUE THREAD

**Issue by olsonpm** [val-town/codemirror-ts#50]
I ran into an issue where I was getting multiple instances of @codemirror/state

[specifically running into this error](https://github.com/codemirror/state/blob/04a4ad7bb0cbc8cb7bfb1781cb0288802c63af57/src/facet.ts#L544)

> Unrecognized extension value in extension set ([object Object]). This sometimes happens because multiple instances of @codemirror/state are loaded, breaking instanceof checks.

I think this would be solved if you added @codemirror/state to the list of peerDependencies

where [you import @codemirror/state here](https://github.com/val-town/codemirror-ts/blob/967412cd5d85a36d679d82c1248b9a90e2df488d/src/facet/tsFacet.ts)

```ts
import { combineConfig, Facet } from "@codemirror/state";
```

and also in tsFacetWorker.ts

I can create a PR unless you need it omitted for some reason

**Comment by tmcw** [comment]
Yep! It should be a peerDependency, I'd definitely accept a PR.
